ARG NODE_VERSION=20
FROM --platform=linux/amd64 node:${NODE_VERSION}-alpine
RUN npm install -g npm@latest \
    && apk add --no-cache icu-libs libc6-compat

WORKDIR /code/timerTrigger
COPY timerTrigger/package*.json ./
RUN npm ci && npm cache clean --force

COPY timerTrigger/ .
RUN npm run build --if-present
RUN npm run test --if-present

EXPOSE 3000
ENTRYPOINT ["npm", "run", "start"]
