ARG NODE_VERSION=22
FROM node:${NODE_VERSION}-alpine
RUN apk add --no-cache icu-libs libc6-compat

WORKDIR /code
COPY package*.json ./
RUN npm ci && npm cache clean --force

COPY . .
RUN npm run build --if-present
RUN npm run test --if-present

ENV LOG_LEVEL=trace
EXPOSE 3000
ENTRYPOINT ["npm", "run", "start"]
