ARG NODE_VERSION=22
FROM node:${NODE_VERSION}-alpine
RUN apk add --no-cache icu-libs libc6-compat

WORKDIR /code/timerTrigger
COPY timerTrigger/package*.json ./
RUN npm ci && npm cache clean --force

COPY timerTrigger/ .
COPY src/graphql.ts src/linear.ts ./src/functions/
RUN npm run build --if-present
RUN npm run test --if-present

EXPOSE 3000
ENTRYPOINT ["npm", "run", "start"]
