ARG NODE_VERSION=18
FROM node:${NODE_VERSION}-alpine
RUN npm install -g npm@latest

COPY . /code
WORKDIR /code/timerTrigger
RUN npm install
RUN npm run build --if-present
RUN npm run test --if-present
ENTRYPOINT npm run start
