services:
  anybot:
    image: anybot-${STAND}
    build:
      context: .
      dockerfile: Dockerfile-anybot
    restart: always
    volumes:
      - "/etc/anybot/${STAND}/.env:/code/.env"
      - "/etc/anybot/${STAND}/private-key.pem:/code/private-key.pem"
    ports:
      - "${ANYBOT_PORT}:3000"
  timerTrigger:
    image: timer-trigger-${STAND}
    build:
      context: .
      dockerfile: Dockerfile-timerTrigger
    restart: always
    ports:
      - "${TIMER_TRIGGER_PORT}:3000"
