services:
  anybot:
    image: anybot
    build:
      context: .
      dockerfile: Dockerfile-anybot
    volumes:
      - /etc/anybot/.env:/code/.env
      - /etc/anybot/private-key.pem:/code/private-key.pem
    ports:
      - 3000:3000
  timerTrigger:
    image: timer-trigger
    build:
      context: .
      dockerfile: Dockerfile-timerTrigger
    ports:
      - 3001:3000

