services:
  anybot:
    image: anybot
    build:
      context: .
      dockerfile: Dockerfile-anybot
  timerTrigger:
    image: timerTrigger
    build:
      context: .
      dockerfile: Dockerfile-timerTrigger
