services:
  anybot:
    image: anybot-${STAND}
    build:
      context: .
      dockerfile: Dockerfile-anybot
    volumes:
      - "/etc/anybot/${STAND}/.env:/code/.env"
      - "/etc/anybot/${STAND}/private-key.pem:/code/private-key.pem"
    ports:
      - "${ANYBOT_PORT}:3000"

  timerTrigger:
    image: timer-trigger-${STAND}
    build:
      context: .
      dockerfile: Dockerfile-timerTrigger
    volumes:
      - "/etc/anybot/${STAND}/timerTrigger/local.settings.json:/code/timerTrigger/local.settings.json"
    ports:
      - "${TIMER_TRIGGER_PORT}:3000"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "${BLOB_PORT}:10000"
    command: azurite-blob --blobHost 0.0.0.0 --blobPort 10000
    volumes:
      - "/var/lib/azurite/${STAND}/data:/data"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
    - 8080:8080
    command:
    - "--enable_metrics=cpu,memory,network"
    - "--store_container_labels=false"
    - "--docker_only=true"
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - anybot
