services:
  anybot:
    image: anybot
    build:
      context: .
      dockerfile: Dockerfile-anybot
  timerTrigger:
    image: timer-trigger
    build:
      context: .
      dockerfile: Dockerfile-timerTrigger
