services:
  anybot:
    image: ghcr.io/anyproto/anybot:${IMAGE_TAG:-local}
    build:
      context: .
      dockerfile: Dockerfile-anybot
    volumes:
      - "/etc/anybot/${STAND}/.env:/code/.env"
      - "/etc/anybot/${STAND}/private-key.pem:/code/private-key.pem"
    ports:
      - "${ANYBOT_PORT}:3000"
    restart: unless-stopped
    environment:
      - "HOST=0.0.0.0"
      - "PORT=3000"

  timerTrigger:
    image: ghcr.io/anyproto/anybot-timer-trigger:${IMAGE_TAG:-local}
    build:
      context: .
      dockerfile: Dockerfile-timerTrigger
    volumes:
      - "/etc/anybot/${STAND}/timerTrigger/local.settings.json:/code/timerTrigger/local.settings.json"
    ports:
      - "${TIMER_TRIGGER_PORT}:3000"
    restart: unless-stopped

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "${BLOB_PORT:-10000}:10000"
      - "${QUEUE_PORT:-10001}:10001"
      - "${TABLE_PORT:-10002}:10002"
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"
    volumes:
      - "/var/lib/azurite/${STAND}/data:/data"
    restart: unless-stopped
