services:
  anybot:
    image: anybot-${STAND}
    build:
      context: .
      dockerfile: Dockerfile-anybot
    restart: always
    volumes:
      - "/etc/anybot/${STAND}/.env:/code/.env"
      - "/etc/anybot/${STAND}/private-key.pem:/code/private-key.pem"
    ports:
      - "${ANYBOT_PORT}:3000"
  timerTrigger:
    image: timer-trigger-${STAND}
    build:
      context: .
      dockerfile: Dockerfile-timerTrigger
    restart: always
    volumes:
      - "/etc/anybot/${STAND}/timerTrigger/local.settings.json:/code/timerTrigger/local.settings.json"
    ports:
      - "${TIMER_TRIGGER_PORT}:3000"
#  azurite:
#    image: mcr.microsoft.com/azure-storage/azurite
#    ports:
#      - "${BLOB_PORT}:10000"
