services:
  anybot:
    image: anybot
    build:
      context: .
      dockerfile: Dockerfile-anybot
    volumes:
      - /etc/anybot/.env:/code/
      - /etc/anybot/private-key.pem:/code/
  timerTrigger:
    image: timer-trigger
    build:
      context: .
      dockerfile: Dockerfile-timerTrigger
