ARG NODE_VERSION=18
FROM node:${NODE_VERSION}-alpine
RUN npm install -g npm@latest

COPY . /code
WORKDIR /code
EXPOSE 3000
RUN npm install
RUN npm run build --if-present
RUN npm run test --if-present
ENV LOG_LEVEL=trace
ENTRYPOINT npm run start
