name: Build and deploy Node.js

on:
  push:
    branches:
      - selfHost
  workflow_dispatch:

env:
  NODE_VERSION: 18

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: restart docker compose
        run: |
          docker-compose stop
          docker-compose up -d
